// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechNest.Api.Data;

#nullable disable

namespace TechNest.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821112550_AddRepairImage")]
    partial class AddRepairImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechNest.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LabelPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TechNest.Api.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiDiagnosticReport")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RepairServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepairServiceId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-001",
                            DeviceModel = "iPhone 13 Pro",
                            EstimatedCost = 0m,
                            IssueDescription = "Screen is completely shattered and touch is not responding.",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AiDiagnosticReport = "Based on the description, the battery has degraded beyond its usable cycle count. Recommend 'Battery Replacement' service.",
                            CreatedAt = new DateTime(2026, 8, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-002",
                            DeviceModel = "MacBook Pro M1",
                            EstimatedCost = 80.00m,
                            IssueDescription = "Battery drains from 100% to 0% in about 30 minutes.",
                            RepairServiceId = 2,
                            Status = 2,
                            UpdatedAt = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUST-003",
                            DeviceModel = "Samsung Galaxy S22",
                            EstimatedCost = 50.00m,
                            IssueDescription = "Dropped in the pool, will not turn on.",
                            RepairServiceId = 3,
                            Status = 3,
                            TechnicianId = 1,
                            UpdatedAt = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TechNest.Api.Models.RepairService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RepairServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 150.00m,
                            Description = "Full display assembly replacement",
                            EstimatedHours = 2,
                            ServiceName = "Screen Replacement"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 80.00m,
                            Description = "New OEM battery installation",
                            EstimatedHours = 1,
                            ServiceName = "Battery Replacement"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 50.00m,
                            Description = "Motherboard cleaning and testing",
                            EstimatedHours = 3,
                            ServiceName = "Water Damage Diagnostics"
                        });
                });

            modelBuilder.Entity("TechNest.Api.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alex@technest.com",
                            FullName = "Alex Fixer",
                            IsAvailable = true,
                            Specialization = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sam@technest.com",
                            FullName = "Sam Coder",
                            IsAvailable = false,
                            Specialization = "Software"
                        });
                });

            modelBuilder.Entity("TechNest.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isblocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechNest.Api.Models.Repair", b =>
                {
                    b.HasOne("TechNest.Api.Models.RepairService", "RepairService")
                        .WithMany()
                        .HasForeignKey("RepairServiceId");

                    b.HasOne("TechNest.Api.Models.Technician", "Technician")
                        .WithMany("AssignedRepairs")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("RepairService");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("TechNest.Api.Models.Technician", b =>
                {
                    b.Navigation("AssignedRepairs");
                });
#pragma warning restore 612, 618
        }
    }
}
